# Generated by Django 4.1.7 on 2023-03-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('last_search', models.DateTimeField(verbose_name='searh date')),
                ('data', models.TextField()),
            ],
        ),
    ]
